---
legacy_cleanup_enabled: false
legacy_cleanup_mask_docker: false
legacy_cleanup_flush_docker_nat: false

legacy_coolify_container_names:
  - coolify
  - coolify-realtime
  - coolify-db
  - coolify-redis
  - coolify-proxy
  - coolify-sentinel

legacy_coolify_paths:
  - /data/coolify
  - /var/lib/coolify
  - /etc/coolify
  - /opt/coolify
  - /root/.coolify
