---
- name: Upgrade k3s server nodes
  hosts: ctrl
  become: true
  roles:
    - role: k3s_server

- name: Upgrade k3s agent nodes
  hosts: ops:build:run
  become: true
  serial: 1
  roles:
    - role: k3s_agent
    - role: gvisor
      when: "'run' in group_names"
    - role: registry_client
